version: "3.4"
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data

  db:
    image: docker.io/library/postgres:13
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
#    image: sohanselise/paperless-ngx-selise
    build:
        context: .
        args:
          QPDF_VERSION: 11.2.0
          PIKEPDF_VERSION: 6.2.8.post1
          PSYCOPG2_VERSION: 2.9.5
          JBIG2ENC_VERSION: 0.29
          TARGETARCH : amd64
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - "80:8000"
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db


volumes:
  data:
  media:
  pgdata:
  redisdata:
