# Generated by Django 4.1.7 on 2023-04-02 05:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1034_alter_document_paid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="document",
            old_name="paid",
            new_name="paid_date",
        ),
    ]
