# Generated by Django 4.1.7 on 2023-04-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1037_alter_document_paid_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="checksum",
            field=models.CharField(
                help_text="The checksum of the original document.",
                max_length=32,
                unique=True,
                verbose_name="checksum",
            ),
        ),
    ]
