# Generated by Django 4.1.7 on 2023-04-02 08:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1039_alter_document_paid_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="document",
            old_name="paid_date",
            new_name="paid",
        ),
    ]
