# Generated by Django 4.1.7 on 2023-04-02 09:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1040_rename_paid_date_document_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="paid",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, verbose_name="paid"
            ),
        ),
    ]
