# Generated by Django 4.1.7 on 2023-04-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1041_alter_document_paid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="paid",
        ),
        migrations.AlterField(
            model_name="document",
            name="checksum",
            field=models.CharField(
                editable=False,
                help_text="The checksum of the original document.",
                max_length=32,
                unique=True,
                verbose_name="checksum",
            ),
        ),
    ]
