# Generated by Django 4.2 on 2023-04-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1043_document_paid_alter_document_checksum"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="paid",
            field=models.DateTimeField(db_index=True, verbose_name="modified"),
        ),
    ]
